### ISSUE TITLE
Image width larger than expected

### ISSUE THREAD

**Issue by cynddl** [guzzle/guzzle_sphinx_theme#21]
The guzzle theme is not expecting images with a width larger than the content.

A simple fix to [guzzle.css_t](https://github.com/guzzle/guzzle_sphinx_theme/blob/master/guzzle_sphinx_theme/guzzle_sphinx_theme/static/guzzle.css_t) would be something like:

```css
.container-wrapper img {
    width: 100%;
}
```
