### ISSUE TITLE
math has colors

### ISSUE THREAD

**Issue by sbonaretti** [guzzle/guzzle_sphinx_theme#36]
Hi,
When using :math:, chars get green. What should I overwrite in css to have black chars? 
Thanks a lot!

<img width="95" alt="screen shot 2018-07-11 at 11 08 28 am" src="https://user-images.githubusercontent.com/13563701/42591167-c6663ae8-84fa-11e8-892b-bfce90d003d8.png">

**Comment by DeoxNA** [comment]
For those still looking for an answer, one solution is to add a CSS file to Sphinx's static files that overrides Guzzle's styling for math elements.

I added a file `_static/css/guzzle_override.css` containing
```css
/**
 * These class styles override the Guzzle defaults, which use #009999 (a light
 * teal) for math elements. 
 */
.m { color: #333333 } /* Literal.Number */
.mf { color: #333333 } /* Literal.Number.Float */
.mh { color: #333333 } /* Literal.Number.Hex */
.mi { color: #333333 } /* Literal.Number.Integer */                                                                                                                                                                                                                                                                    
.mo { color: #333333 } /* Literal.Number.Oct */
.mn { color: #333333 } /* Literal.Number.Number */
.mrow { color: #333333 } /* Literal.Number.Row */
```
You need to add this file to your CSS sources by adding the following to your `conf.py`
```
html_css_files = ['css/guzzle_override.css']
```
